name: docker-push

# TODO: Once we get this into production, see what inputs we care about.
on:
  workflow_dispatch:
    inputs:
      deploy_ref:
        description: "The branch, tag or SHA to make into a Docker image."
        required: true
        default: "master"
      platforms:
        description: "Comma-separated list of platform(s) to build an image for"
        required: true
        default: "linux/amd64"
  push:
    branches:
      - "master"
  pull_request:
    branches: 
      - "master"

# Add permissions block here
permissions:
  id-token: write
  contents: read

env:
  AWS_DEFAULT_REGION: us-east-2
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Empty ref shows up as "Pull the commit we used to deploy this with"
          ref: ${{ github.event.inputs.deploy_ref }}
        # It remains insanely annoying that this is required b/c github.sha
        # doesn't get the sha we just checked out
      - name: "Get GIT SHA"
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 386145735201.dkr.ecr.us-east-2.amazonaws.com/trm-takehome
          tags: |
            type=ref,event=branch
            type=raw,value=${{ format('sha-{0}', steps.sha.outputs.sha) }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::386145735201:role/github-actions-role
          aws-region: us-east-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: src
          file: src/Dockerfile
          platforms: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}
          build-args: "AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          no-cache: true

  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: terraform plan
        run: |
          cd terraform/helm/
          terraform init
          terraform plan -out=plan.out
          cat plan.out
      - name: write plan.out to the PR only if a PR triggered this workflow
        if: github.event_name == 'pull_request'
        run: |
          echo "plan=$(cat plan.out)" | gh pr comment ${{ github.event.pull_request.number }} --body-file - || gh pr comment ${{ github.event.pull_request.number }} --body "Failed to write plan.out to the PR"

